#Aaryan Beniwal 102353014 3C53

##Importing

In [2]:
import  numpy as np

##Q1

###Q1 (a)

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
rev = np.flip(arr)
print(rev)

[5 4 6 3 2 1]


###Q1 (b)

In [ ]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_method1 = array1.flatten()
flattened_method2 = array1.reshape(-1)
print("(method 1 - flatten()):", flattened_method1)
print("(method 2 - reshape(-1)):", flattened_method2)

(method 1 - flatten()): [1 2 3 2 4 5 1 2 3]
(method 2 - reshape(-1)): [1 2 3 2 4 5 1 2 3]


###Q1 (c)

In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
comparison_result = (arr1 == arr2)
print(comparison_result)

[[ True  True]
 [ True  True]]


###Q1 (d)

In [ ]:
import numpy as np
from collections import Counter

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
counts_x = Counter(x)
most_common_x = counts_x.most_common(1)
most_frequent_value_x = most_common_x[0][0]
indices_x = np.where(x == most_frequent_value_x)[0]
print(most_frequent_value_x)
print(indices_x)

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
counts_y = Counter(y)
most_common_y = counts_y.most_common(1)
most_frequent_value_y = most_common_y[0][0]
indices_y = np.where(y == most_frequent_value_y)[0]
print(most_frequent_value_y)
print(indices_y)

1
[0 5 7 8 9]
1
[0 1 2]


###Q1 (e)

In [ ]:
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

sum_all_elements = np.sum(gfg)
print(sum_all_elements)

sum_row_wise = np.sum(gfg, axis=1)
print(sum_row_wise)

sum_column_wise = np.sum(gfg, axis=0)
print(sum_column_wise)

45
[[14]
 [16]
 [15]]
[[20  9 16]]


###Q1 (f)

In [ ]:
import numpy as np

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

sum_diagonal = np.trace(n_array)
print(sum_diagonal)

eigen_values = np.linalg.eigvals(n_array)
print(eigen_values)

eigen_values, eigen_vectors = np.linalg.eig(n_array)
print(eigen_vectors)

inverse_matrix = np.linalg.inv(n_array)
print(inverse_matrix)

determinant = np.linalg.det(n_array)
print(determinant)

176
[98.16835147 28.097044   49.73460452]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
137180.0000000001


###Q1 (g)

In [ ]:
import numpy as np

p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])

multiplication_1 = np.dot(p1, q1)
print(multiplication_1)

covariance_1 = np.cov(p1, q1)
print(covariance_1)

q2 = np.array([[4, 5, 1], [6, 7, 2]])
p2 = np.array([[1, 2], [2, 3], [4, 5]])

multiplication_2 = np.dot(p2, q2)
print(multiplication_2)

covariance_2_p_flat = np.cov(p2.flatten())
print(covariance_2_p_flat)

[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
[[16 19  5]
 [26 31  8]
 [46 55 14]]
2.1666666666666665


###Q1 (h)

In [ ]:
import numpy as np

x_mat = np.array([[2, 3, 4], [3, 2, 9]])
y_mat = np.array([[1, 5, 0], [5, 10, 3]])

if x_mat.shape[1] == y_mat.shape[0]:
    inner_product_xy = np.dot(x_mat, y_mat)
    print(inner_product_xy)
elif x_mat.shape[0] == y_mat.shape[1]:
    inner_product_yx = np.dot(y_mat, x_mat)
    print(inner_product_yx)
else:
    element_wise_product = x_mat * y_mat
    print(element_wise_product)

outer_product = np.outer(x_mat.flatten(), y_mat.flatten())
print(outer_product)

cartesian_product = np.kron(x_mat, y_mat)
print(cartesian_product)

[[ 2 15  0]
 [15 20 27]]
[[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
[[ 2 10  0  3 15  0  4 20  0]
 [10 20  6 15 30  9 20 40 12]
 [ 3 15  0  2 10  0  9 45  0]
 [15 30  9 10 20  6 45 90 27]]


##Q2

###Q2 (a)

In [3]:
#1)
array = np.array([[1, -2, 3],[-4, 5, -6]])

mod_val=np.abs(array)
print(mod_val)

#2
flat_percentiles = np.percentile(array, [25, 50, 75])
print("\nPercentiles (Flattened array):", flat_percentiles)

# Column-wise
col_percentiles = np.percentile(array, [25, 50, 75], axis=0)
print("\nColumn-wise percentiles:\n", col_percentiles)

# Row-wise
row_percentiles = np.percentile(array, [25, 50, 75], axis=1)
print("\nRow-wise percentiles:\n", row_percentiles)

#3

# Flattened
print("Flattened:")
print("Mean:", np.mean(array))
print("Median:", np.median(array))
print("Standard Deviation:", np.std(array))

# Column-wise
print("\nColumn-wise:")
print("Mean:", np.mean(array, axis=0))
print("Median:", np.median(array, axis=0))
print("Standard Deviation:", np.std(array, axis=0))

# Row-wise
print("\nRow-wise:")
print("Mean:", np.mean(array, axis=1))
print("Median:", np.median(array, axis=1))
print("Standard Deviation:", np.std(array, axis=1))

[[1 2 3]
 [4 5 6]]

Percentiles (Flattened array): [-3.5 -0.5  2.5]

Column-wise percentiles:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]

Row-wise percentiles:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Flattened:
Mean: -0.5
Median: -0.5
Standard Deviation: 3.8622100754188224

Column-wise:
Mean: [-1.5  1.5 -1.5]
Median: [-1.5  1.5 -1.5]
Standard Deviation: [2.5 3.5 4.5]

Row-wise:
Mean: [ 0.66666667 -1.66666667]
Median: [ 1. -4.]
Standard Deviation: [2.05480467 4.78423336]


###Q2 (b)

In [4]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

floor_vals = np.floor(a)
ceil_vals = np.ceil(a)
trunc_vals = np.trunc(a)
round_vals = np.round(a)

print("Original:   ", a)
print("Floor:      ", floor_vals)
print("Ceiling:    ", ceil_vals)
print("Truncated:  ", trunc_vals)
print("Rounded:    ", round_vals)


Original:    [-1.8 -1.6 -0.5  0.5  1.6  1.8  3. ]
Floor:       [-2. -2. -1.  0.  1.  1.  3.]
Ceiling:     [-1. -1. -0.  1.  2.  2.  3.]
Truncated:   [-1. -1. -0.  0.  1.  1.  3.]
Rounded:     [-2. -2. -0.  0.  2.  2.  3.]


##Q3

###Q3 (a)

In [5]:
array = np.array([10, 52, 62, 16, 16, 54, 453])

sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

# ii
sorted_indices = np.argsort(array)
print("Indices of sorted array:", sorted_indices)

# iii.
smallest_4 =sorted_array[:4]
print("4 smallest elements:", smallest_4)

# iv.
largest_5 = np.sort(array)[-5:][::-1]
print("5 largest elements:", largest_5)

Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [453  62  54  52  16]


###Q3 (b)

In [6]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

#
int_ele = array[array % 1 == 0]
print("Integer elements:", int_ele)

#
float_ele = array[array % 1 != 0]
print("Float elements:", float_ele)

Integer elements: [1. 2. 3. 2.]
Float elements: [1.2 2.2]


##Q4

###Q4 (a)

In [8]:
from google.colab import files
uploaded = files.upload()

Saving Nikon-D500-Sample-Image-3.jpg to Nikon-D500-Sample-Image-3.jpg


###Q4 (b)

In [9]:
from PIL import Image, ImageFile
import numpy as np

ImageFile.LOAD_TRUNCATED_IMAGES = True

def img_to_array(path):
    try:
        img = Image.open(path)
        img_arr = np.array(img)

        if img_arr.ndim == 2:
            print("Grayscale image detected")
            np.savetxt("image_grayscale.txt", img_arr, fmt='%d')
            return "grayscale"

        elif img_arr.ndim == 3:
            print("RGB image detected")
            flat = img_arr.reshape(-1, img_arr.shape[2])
            np.savetxt("image_rgb.txt", flat, fmt='%d')
            return "rgb"

        else:
            print("Image format not recognized")
            return None

    except Exception as e:
        print("Error:", e)
        return None

image_type = img_to_array("Nikon-D500-Sample-Image-3.jpg")

# Load the saved file based on type
if image_type == "grayscale":
    gray = np.loadtxt("image_grayscale.txt", dtype=int)
    print("Loaded grayscale shape:", gray.shape)
    print(gray[:5])  # Print only a part
elif image_type == "rgb":
    rgb = np.loadtxt("image_rgb.txt", dtype=int)
    print("Loaded RGB shape:", rgb.shape)
    print(rgb[:5])  # Print only a part

else:
    print("Could not load the saved image data.")


RGB image detected
Loaded RGB shape: (658028, 3)
[[106  44  57]
 [106  44  55]
 [107  44  53]
 [110  45  51]
 [112  46  50]]
